services:
  # MySQL Database
  database:
    build: ./database
    container_name: financial-freedom-db
    environment:
      MYSQL_ROOT_PASSWORD: financial_freedom_root
      MYSQL_DATABASE: financial_freedom
      MYSQL_USER: financial_user
      MYSQL_PASSWORD: financial_pass
    ports:
      - "6002:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - financial-freedom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pfinancial_freedom_root"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flask Backend API
  backend:
    build: ./backend
    container_name: financial-freedom-backend
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: financial_user
      DB_PASSWORD: financial_pass
      DB_NAME: financial_freedom
    ports:
      - "5007:5006"
    volumes:
      - ./backend:/app
    networks:
      - financial-freedom-network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006/api/debts/summary"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build: ./frontend
    container_name: financial-freedom-frontend
    environment:
      REACT_APP_API_URL: http://localhost:5007
    ports:
      - "3002:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - financial-freedom-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: financial-freedom-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - financial-freedom-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db_data:

networks:
  financial-freedom-network:
    driver: bridge
